### PR TITLE
make webhook to use local nad cache

### LINKED ISSUE #101: resource not injected in a large K8s cluster
When we bringup a deployment which has 100 pod replicas, then some pods are not created because NRI doesn't inject required SRIOV VF resources into the pod. 
From troubleshooting NRI (of course logging has to be improved by writing pod info as well in the logs), it looks NRI takes around 15 secs (because of GC ?) to respond to admission request for the failed pod whereas it just look  around 5 secs for the working pods. is admission response ignored due to timeout ? it happens though webhook timeout set to 30 sec (default value?). 
After changing `failurePolicy` from `Ignore` to `Fail`, then all pods are injected with resources. Does Fail policy make any difference ? As per the documentation, it says it would cause pod admission to fail. isn't it ?
If `Fail` policy fixes the issue, then we would need to make `failurePolicy` as configurable parameter, currently it's [hardcoded](https://github.com/k8snetworkplumbingwg/network-resources-injector/blob/628f2982daf036a97ca759efd2a633bd287298ff/pkg/installer/installer.go#L134) to use `Ignore` policy.

### PR DESCRIPTION
**Pull request by pperiyasamy**
this implements local cache using network-attachment-definition-client's informer, web hook looks up this cache, fall back to K8 api when entry is not found.

Fixes #101 

Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

### CODE REVIEW

File: cmd/webhook/main.go [hunk 1]
```diff
@@ -193,4 +199,7 @@ func main() {
 			webhook.SetCustomizedInjections(cm)
 		}
 	}
+
+	// TODO: find a way to stop cache, should we run the above block in a go routine and make main module
```
Comment (pperiyasamy) [inline cmd/webhook/main.go:203]: @martinkennelly @zshi-redhat shall I make to run above for block into a goroutine, exit gracefully on term signal ? this change would also enable to stop nad cache informer.

or is the above for block intentional ?

Comment (pperiyasamy) [reply cmd/webhook/main.go:203]: looks this issue is being addressed in this [PR](https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/62), will update it here once that PR is merged.

**Review by zshi-redhat — APPROVED** [review]

File: pkg/tools/cache.go [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+
+func (nc *NetAttachDefCache) put(networkName string, annotations map[string]string) {
+	nc.networkAnnotationsMapMutex.Lock()
+	nc.networkAnnotationsMap[networkName] = annotations
+	nc.networkAnnotationsMapMutex.Unlock()
+}
+
+// Get returns annotations map for the given network name, if it's not available
+// return nil
+func (nc *NetAttachDefCache) Get(networkName string) map[string]string {
```
Comment (martinkennelly) [inline pkg/tools/cache.go:94]: small nit - feel free to ignore: up to you if you want to change it - it would be better to have two arguments here  I think - namespace and nad name, then you can bury the joining of the two strings ```net.Namespace + "/" + net.Name``` in this function instead of having to do it consistently when calling it like  I see below.  WDYT?

File: pkg/webhook/webhook.go [hunk 3]
```diff
@@ -367,18 +369,24 @@ func getNetworkAttachmentDefinition(namespace, name string) (*cniv1.NetworkAttac
...
 func parseNetworkAttachDefinition(net *multus.NetworkSelectionElement, reqs map[string]int64, nsMap map[string]string) (map[string]int64, map[string]string, error) {
 	/* for each network in annotation ask API server for network-attachment-definition */
-	networkAttachmentDefinition, err := getNetworkAttachmentDefinition(net.Namespace, net.Name)
-	if err != nil {
-		/* if doesn't exist: deny pod */
-		reason := errors.Wrapf(err, "could not find network attachment definition '%s/%s'", net.Namespace, net.Name)
-		glog.Error(reason)
-		return reqs, nsMap, reason
+	var annotationsMap map[string]string
+	annotationsMap = nadCache.Get(net.Namespace + "/" + net.Name)
```
Comment (martinkennelly) [inline pkg/webhook/webhook.go:373]: nit: why not ":="  save one line :P

File: pkg/tools/cache.go [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+	Stop()
+	Get(string) map[string]string
+}
+
+func Create() NetAttachDefCacheService {
+	return &NetAttachDefCache{make(map[string]map[string]string),
+		&sync.Mutex{}, make(chan struct{})}
+}
+
+// Start start the informer for NetworkAttachmentDefinition, upon events populate the cache
```
[the remark this answers is not in the document]
Comment (pperiyasamy) [reply pkg/tools/cache.go]: done

File: pkg/tools/cache.go [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+func (nc *NetAttachDefCache) Start() {
+	factory := externalversions.NewFilteredSharedInformerFactory(setupNetAttachDefClient(), 0, "", func(o *metav1.ListOptions) {})
```
[the remark this answers is not in the document]
Comment (pperiyasamy) [reply pkg/tools/cache.go]: done

File: pkg/tools/cache.go [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+			netAttachDef := obj.(*cniv1.NetworkAttachmentDefinition)
+			nc.remove(netAttachDef.Namespace + "/" + netAttachDef.Name)
+		},
+	})
+	go informer.Run(nc.stopper)
+}
+
+// Stop stop the NetworkAttachmentDefinition informer
+func (nc *NetAttachDefCache) Stop() {
+	close(nc.stopper)
```
[the remark this answers is not in the document]
Comment (pperiyasamy) [reply pkg/tools/cache.go:92]: good find! now added a code for graceful shutdown of nad cache with atomic isRunning variable, hope that's ok now.

File: pkg/tools/cache.go (hunk 2 above)
Comment (pperiyasamy) [reply pkg/tools/cache.go]: yes, it makes sense. done.

File: pkg/tools/cache.go [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+	defer nc.networkAnnotationsMapMutex.Unlock()
+	if annotationsMap, exists := nc.networkAnnotationsMap[networkName]; exists {
+		return annotationsMap
+	}
+	return nil
+}
+
+func (nc *NetAttachDefCache) remove(networkName string) {
+	nc.networkAnnotationsMapMutex.Lock()
+	delete(nc.networkAnnotationsMap[networkName], networkName)
```
[the remark this answers is not in the document]
Comment (pperiyasamy) [reply pkg/tools/cache.go]: done.

File: pkg/webhook/webhook.go (hunk 3 above)
Comment (pperiyasamy) [reply pkg/webhook/webhook.go]: done

File: pkg/tools/cache.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (martinkennelly) [reply pkg/tools/cache.go:92]: @pperiyasamy I don't understand how atomic.StoreInt32 solves the issue. I don't think the issue with the informer is possible to solve without the informer signally back that it has completed/ended and there isn't any way to do this, it seems.

File: pkg/tools/cache.go [hunk 8]
```diff
@@ -0,0 +1,147 @@
...
+			defer mutex.Unlock()
+			netAttachDef := obj.(*cniv1.NetworkAttachmentDefinition)
+			nc.remove(netAttachDef.Namespace, netAttachDef.Name)
+		},
+	})
+	go func() {
+		atomic.StoreInt32(&(nc.isRunning), int32(1))
+		// informer Run blocks until informer is stopped
+		glog.Infof("starting net-attach-def informer")
+		informer.Run(nc.stopper)
```
Comment (martinkennelly) [inline pkg/tools/cache.go:85]: Can we put in a log after .Run "net-attach-def informer stopped"? It may aid debugging.

**Review by martinkennelly — COMMENTED** [review]
LGTM - just small change required. Thanks Peri for the changes!!

File: pkg/tools/cache.go (hunk 8 above)
Comment (pperiyasamy) [reply pkg/tools/cache.go:85]: done

File: pkg/tools/cache.go [hunk 9]
```diff
@@ -0,0 +1,147 @@
...
+		atomic.StoreInt32(&(nc.isRunning), int32(0))
+	}()
+}
+
+// Stop teardown the NetworkAttachmentDefinition informer
+func (nc *NetAttachDefCache) Stop() {
+	close(nc.stopper)
+	func(limit time.Duration) {
```
[the remark this answers is not in the document]
Comment (pperiyasamy) [reply pkg/tools/cache.go]: yes :) done.

**Review by martinkennelly — APPROVED** [review]
I have verified this change with #98 ! Thanks @pperiyasamy for all your hard work and changes here! I am waiting on @zshi-redhat to review this now as there are changes since he last approved.

File: pkg/tools/cache.go [hunk 10]
```diff
@@ -0,0 +1,145 @@
...
+		informer.Run(nc.stopper)
+		glog.Infof("net-attach-def informer is stopped")
+		atomic.StoreInt32(&(nc.isRunning), int32(0))
+	}()
+}
+
+// Stop teardown the NetworkAttachmentDefinition informer
+func (nc *NetAttachDefCache) Stop() {
+	close(nc.stopper)
+	tEnd := time.Now().Add(3 * time.Second)
```
Comment (MichalGuzieniuk) [inline pkg/tools/cache.go:94]: Could you explain why you choose 3 seconds? Is this enough to stop net-attach-def informer?

Comment (pperiyasamy) [reply pkg/tools/cache.go:94]: @MichalGuzieniuk thanks for looking at this. I just chose 3 seconds based on Kubelet's default shutdown grace period (i.e. 30 sec) for a pod. but, yes, if net-attach-def events are not yet flushed away from informer then it might take a while for informer to return after close. 
there is no much activity happening in this cache module apart from updating its local map, do you see this as a problem or any other concern ?

Comment (MichalGuzieniuk) [reply pkg/tools/cache.go:94]: Fine for me. I was just interested if you choose this value because in tests you discovered that is the best or had other reason behind.

**Comment by zshi-redhat** [comment]
> I have verified this change with #98 ! Thanks @pperiyasamy for all your hard work and changes here! I am waiting on @zshi-redhat to review this now as there are changes since he last approved.

Thanks for all the changes and reviews!
